version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - weather_net

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://weather_user:weather_password@postgres:5432/weather_db
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    networks:
      - weather_net
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - weather_net
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  postgres_data:

networks:
  weather_net:
    driver: bridge